### ISSUE TITLE
Segmentation fault on stable, gfortran 6.4.0/7.3.0/8.0.1

### ISSUE THREAD

**Issue by srk** [aoterodelaroza/critic2#13]
Hello,
After downloading the stable branch to fix a previous problem, I encountered another. I gave the following input:
```
MOLECULE tetrahedrane.wfx
LOAD tetrahedrane.wfx
AUTO
CPREPORT VERYLONG
```
I get segmentation faults right away:
```
+ critic2 (development), commit d8111dd
 compile host: Linux NOMS 4.4.0-122-generic #146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 compile date: Sun 27 May 05:56:27 BST 2018
    using f77: gfortran-8 -g -O2 
          f90: gfortran-8 -g -O2 -ffree-form -ffree-line-length-none -fopenmp
            c: gcc-8 -g -O2 -Iqhull/
      ldflags: 
       debug?: no
 compiled dat: /opt/CCCE/critic2/share/critic2
      datadir: /opt/CCCE/critic2/share/critic2
     dic file: /opt/CCCE/critic2/share/critic2/cif_core.dic
...was found?: T

CRITIC2--2018/5/27, 05:56:33.560

%% MOLECULE tetrahedrane.wfx


Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f0291d7a3da in ???
#1  0x7f0291d79603 in ???
#2  0x7f02912774af in ???
#3  0x4d6826 in __crystalmod_MOD_find_asterisms
	at /home/srk/install/Science/critic2/stable/src/crystalmod@proc.f90:1088
#4  0x4da9ea in __crystalmod_MOD_struct_fill
	at /home/srk/install/Science/critic2/stable/src/crystalmod@proc.f90:589
#5  0x60c2e0 in __systemmod_MOD_new_from_seed
	at /home/srk/install/Science/critic2/stable/src/systemmod@proc.f90:364
#6  0x5e4112 in __struct_drivers_MOD_struct_crystal_input
	at /home/srk/install/Science/critic2/stable/src/struct_drivers@proc.f90:219
#7  0x40397c in critic
	at /home/srk/install/Science/critic2/stable/src/critic2.F90:117
#8  0x40339c in main
	at /home/srk/install/Science/critic2/stable/src/critic2.F90:25
Segmentation fault (core dumped)
```
I tried compiling with gfortran 6.4.0, 7.3.0 and 8.0.1 and all the executables gave the same result.

**Comment by aoterodelaroza** [comment]
The stable branch does not have cystalmod@proc.f90. That must be the development branch. In any case, it looks like a bug. I suspect your wfx has ghost atoms but, just in case, can you please send me the wfx file?

**Comment by aoterodelaroza** [comment]
That's odd. This wfx does not have an "Atomic Numbers" section. Was this generated by Gaussian or by some other program?

**Comment by srk** [comment]
This is a standard example file provided with Todd Keith's AIMAll.

**Comment by aoterodelaroza** [comment]
Alright, I've just pushed some changes to both versions and I think it should work now. Can you please pull and try again?

**Comment by srk** [comment]
I'll try it, thanks!

**Comment by srk** [comment]
Recompiled just now with gfortran 8.0.1. This example file works fine now, thanks!
